version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    depends_on:
      - db  
  
  db:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: webapisqldb
    environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: "Bassword@123"
    ports:  
      - '1433:1433'  
    expose:  
      - 1433
    volumes:  
      - sql-data:/var/opt/mssql3  

volumes:
      sql-data:
